import {SidebarsConfig} from '@docusaurus/plugin-content-docs';

export const sidebarAdrs: SidebarsConfig = {
  adrs: [
    {
      type: 'category',
      label: 'Architectural Decision Records',
      link: {
        type: 'generated-index',
        description: "This page contains a list of accepted Oasis ADRs. To see the currently discussed ADRs or to open a new ADR, visit the official oasisprotocol/adrs repository on github.com.",
        slug: '/adrs',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'adrs',
        },
      ],
    }
  ],
};
