// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  oasisNetworkPrimer: [{
    type: 'autogenerated',
    dirName: '.',
  }],
};

module.exports = sidebars;
